### ISSUE TITLE
convert-roms failing on macOS

### ISSUE THREAD

**Issue by aarongeorge** [alucryd/oxyromon#105]
Here is the output log when trying to convert ROM files to ZIP

Command
`RUST_BACKTRACE=full ./oxyromon convert-roms --format ZIP --all`

Output
```
Processing "Nintendo - Game Boy"
Compressing "Pri Pri - Primitive Princess! (Japan).gb"
⠁ Compressing files                                                                                          thread 'main' panicked at src/sevenzip.rs:169:10:
Failed to add files to archive: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:        0x100d439a0 - std::backtrace_rs::backtrace::libunwind::trace::hf755a955ad018943
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x100d439a0 - std::backtrace_rs::backtrace::trace_unsynchronized::hde69ab8e2b667964
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100d439a0 - std::sys_common::backtrace::_print_fmt::hf6c414569af631f5
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x100d439a0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0524bd1b527203b8
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x100d65938 - core::fmt::rt::Argument::fmt::ha0532872e39381ee
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
   5:        0x100d65938 - core::fmt::write::h74be1333b0a6ddea
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
   6:        0x100d3fc9c - std::io::Write::write_fmt::h6c011b665b2d7d4b
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
   7:        0x100d437e0 - std::sys_common::backtrace::_print::hcc60dadc0e4df78f
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x100d437e0 - std::sys_common::backtrace::print::he25ff7dac6402434
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x100d44de0 - std::panicking::default_hook::{{closure}}::h41763ba018b93bf7
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
  10:        0x100d44af8 - std::panicking::default_hook::h017c44660373840e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
  11:        0x100d45324 - std::panicking::rust_panic_with_hook::h221a0baf52ecd48a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:731:13
  12:        0x100d4522c - std::panicking::begin_panic_handler::{{closure}}::h18b661cf0f97a414
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
  13:        0x100d43e2c - std::sys_common::backtrace::__rust_end_short_backtrace::h4f4b2ffab2311217
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
  14:        0x100d44f98 - rust_begin_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
  15:        0x100da3124 - core::panicking::panic_fmt::hd6070cd222575be5
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
  16:        0x100da347c - core::result::unwrap_failed::h54ffffcb65858936
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
  17:        0x100676e44 - oxyromon::sevenzip::add_files_to_archive::h5d8abba081cac1d4
  18:        0x100553978 - oxyromon::convert_roms::to_archive::{{closure}}::hcc6cf413d5b5e297
  19:        0x100545f20 - oxyromon::convert_roms::main::{{closure}}::h29b0b0779223a4e5
  20:        0x1005c9358 - oxyromon::main::main::{{closure}}::hffde4f61befebadc
  21:        0x1005318dc - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::h496761028b8f4178
  22:        0x1007b01d4 - <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll::hf8f1670a6f14cb1b
  23:        0x1007d4198 - async_io::driver::block_on::hae4b2aa77a6b8866
  24:        0x100756654 - async_global_executor::executor::block_on::hc6d855af4fe23ec3
  25:        0x100531ec8 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::h673db11c35276e2f
  26:        0x1006257e4 - async_std::task::builder::Builder::blocking::h5e00fa867591bd0c
  27:        0x1007b52f4 - oxyromon::main::h538c6899c0f19e05
  28:        0x1007e11b4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0ce627b51f25e033
  29:        0x1008425f0 - std::rt::lang_start::{{closure}}::h92ff3f4bf9e74bba
  30:        0x100d39638 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44482c562109b08c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:284:13
  31:        0x100d39638 - std::panicking::try::do_call::h627d61d518625eaf
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  32:        0x100d39638 - std::panicking::try::h487b8df834773e7d
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  33:        0x100d39638 - std::panic::catch_unwind::h5d4366c6f71d3443
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  34:        0x100d39638 - std::rt::lang_start_internal::{{closure}}::h749338e1cc06c4f7
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:48
  35:        0x100d39638 - std::panicking::try::do_call::h2098bd254e5cae95
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  36:        0x100d39638 - std::panicking::try::h7bfd8a0246bca0f8
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  37:        0x100d39638 - std::panic::catch_unwind::h6da51257cc975c65
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  38:        0x100d39638 - std::rt::lang_start_internal::h5f00c09289a72e67
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:20
  39:        0x1007b533c - _main
```

Running:
Apple M1 Max
macOS 13.5.1 (22G90)
oxyromon 0.17.0

**Comment by alucryd** [comment]
Sounds like you don't have 7z installed on your system. The 7z binary list be in your `PATH`.

**Comment by alucryd** [comment]
I need to add checks for the required binaries to avoid printing stacktraces like these, adding to my to-do list.

**Comment by aarongeorge** [comment]
Ahh good point! That would be good to throw that it's not installed.

On macOS when installing with brew 7z is installed as 7zz, so a symlink was required. Turns out an alias as 7z in zsh didn't work

**Comment by alucryd** [comment]
https://github.com/alucryd/oxyromon/commit/4943128372c750ea627701b27daa8141ff2e094f should behave a lot better now. Also using `7zz` on macos now so you don't have to create a symlink anymore.
